# Intro

In [8]:
%load_ext autoreload
%autoreload 2

import polars as pl
import polars.selectors as cs

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [32]:
df = pl.DataFrame({
    "species": ["Adelie", "Adelie", "Gentoo", "Gentoo", "Chinstrap"],
    "island":  ["Torgersen", "Biscoe", "Biscoe", "Biscoe", "Dream"],
    "bill_mm": [39.1, 37.8, 46.1, 50.0, 46.5],
    "mass_g":  [3750, 3400, 4500, 5700, None],
})
df

shape: (5, 4)
┌───────────┬───────────┬─────────┬────────┐
│ species   ┆ island    ┆ bill_mm ┆ mass_g │
│ ---       ┆ ---       ┆ ---     ┆ ---    │
│ str       ┆ str       ┆ f64     ┆ i64    │
╞═══════════╪═══════════╪═════════╪════════╡
│ Adelie    ┆ Torgersen ┆ 39.1    ┆ 3750   │
│ Adelie    ┆ Biscoe    ┆ 37.8    ┆ 3400   │
│ Gentoo    ┆ Biscoe    ┆ 46.1    ┆ 4500   │
│ Gentoo    ┆ Biscoe    ┆ 50.0    ┆ 5700   │
│ Chinstrap ┆ Dream     ┆ 46.5    ┆ null   │
└───────────┴───────────┴─────────┴────────┘

In [33]:
df.columns

['species', 'island', 'bill_mm', 'mass_g']

In [34]:
df.schema

Schema([('species', String),
        ('island', String),
        ('bill_mm', Float64),
        ('mass_g', Int64)])

In [35]:
df.glimpse()    # yes, it's literally dplyr::glimpse()

Rows: 5
Columns: 4
$ species <str> 'Adelie', 'Adelie', 'Gentoo', 'Gentoo', 'Chinstrap'
$ island  <str> 'Torgersen', 'Biscoe', 'Biscoe', 'Biscoe', 'Dream'
$ bill_mm <f64> 39.1, 37.8, 46.1, 50.0, 46.5
$ mass_g  <i64> 3750, 3400, 4500, 5700, null

In [36]:
df.describe()

shape: (9, 5)
┌────────────┬─────────┬───────────┬─────────┬─────────────┐
│ statistic  ┆ species ┆ island    ┆ bill_mm ┆ mass_g      │
│ ---        ┆ ---     ┆ ---       ┆ ---     ┆ ---         │
│ str        ┆ str     ┆ str       ┆ f64     ┆ f64         │
╞════════════╪═════════╪═══════════╪═════════╪═════════════╡
│ count      ┆ 5       ┆ 5         ┆ 5.0     ┆ 4.0         │
│ null_count ┆ 0       ┆ 0         ┆ 0.0     ┆ 1.0         │
│ mean       ┆ null    ┆ null      ┆ 43.9    ┆ 4337.5      │
│ std        ┆ null    ┆ null      ┆ 5.22159 ┆ 1017.656622 │
│ min        ┆ Adelie  ┆ Biscoe    ┆ 37.8    ┆ 3400.0      │
│ 25%        ┆ null    ┆ null      ┆ 39.1    ┆ 3750.0      │
│ 50%        ┆ null    ┆ null      ┆ 46.1    ┆ 4500.0      │
│ 75%        ┆ null    ┆ null      ┆ 46.5    ┆ 4500.0      │
│ max        ┆ Gentoo  ┆ Torgersen ┆ 50.0    ┆ 5700.0      │
└────────────┴─────────┴───────────┴─────────┴─────────────┘

In [37]:
df.null_count()

shape: (1, 4)
┌─────────┬────────┬─────────┬────────┐
│ species ┆ island ┆ bill_mm ┆ mass_g │
│ ---     ┆ ---    ┆ ---     ┆ ---    │
│ u32     ┆ u32    ┆ u32     ┆ u32    │
╞═════════╪════════╪═════════╪════════╡
│ 0       ┆ 0      ┆ 0       ┆ 1      │
└─────────┴────────┴─────────┴────────┘

In [38]:
df.select(cs.numeric())

shape: (5, 2)
┌─────────┬────────┐
│ bill_mm ┆ mass_g │
│ ---     ┆ ---    │
│ f64     ┆ i64    │
╞═════════╪════════╡
│ 39.1    ┆ 3750   │
│ 37.8    ┆ 3400   │
│ 46.1    ┆ 4500   │
│ 50.0    ┆ 5700   │
│ 46.5    ┆ null   │
└─────────┴────────┘

In [39]:
df.select(cs.string())

shape: (5, 2)
┌───────────┬───────────┐
│ species   ┆ island    │
│ ---       ┆ ---       │
│ str       ┆ str       │
╞═══════════╪═══════════╡
│ Adelie    ┆ Torgersen │
│ Adelie    ┆ Biscoe    │
│ Gentoo    ┆ Biscoe    │
│ Gentoo    ┆ Biscoe    │
│ Chinstrap ┆ Dream     │
└───────────┴───────────┘

In [44]:
df.with_columns(z = pl.col("bill_mm") + pl.col("mass_g"))

shape: (5, 5)
┌───────────┬───────────┬─────────┬────────┬────────┐
│ species   ┆ island    ┆ bill_mm ┆ mass_g ┆ z      │
│ ---       ┆ ---       ┆ ---     ┆ ---    ┆ ---    │
│ str       ┆ str       ┆ f64     ┆ i64    ┆ f64    │
╞═══════════╪═══════════╪═════════╪════════╪════════╡
│ Adelie    ┆ Torgersen ┆ 39.1    ┆ 3750   ┆ 3789.1 │
│ Adelie    ┆ Biscoe    ┆ 37.8    ┆ 3400   ┆ 3437.8 │
│ Gentoo    ┆ Biscoe    ┆ 46.1    ┆ 4500   ┆ 4546.1 │
│ Gentoo    ┆ Biscoe    ┆ 50.0    ┆ 5700   ┆ 5750.0 │
│ Chinstrap ┆ Dream     ┆ 46.5    ┆ null   ┆ null   │
└───────────┴───────────┴─────────┴────────┴────────┘

In [46]:
df["island"].value_counts(sort = True)

shape: (3, 2)
┌───────────┬───────┐
│ island    ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ Biscoe    ┆ 3     │
│ Torgersen ┆ 1     │
│ Dream     ┆ 1     │
└───────────┴───────┘

In [50]:
df.group_by("species", "island").len()

shape: (4, 3)
┌───────────┬───────────┬─────┐
│ species   ┆ island    ┆ len │
│ ---       ┆ ---       ┆ --- │
│ str       ┆ str       ┆ u32 │
╞═══════════╪═══════════╪═════╡
│ Adelie    ┆ Biscoe    ┆ 1   │
│ Adelie    ┆ Torgersen ┆ 1   │
│ Chinstrap ┆ Dream     ┆ 1   │
│ Gentoo    ┆ Biscoe    ┆ 2   │
└───────────┴───────────┴─────┘

In [40]:
df.select(cs.starts_with("bill"))

shape: (5, 1)
┌─────────┐
│ bill_mm │
│ ---     │
│ f64     │
╞═════════╡
│ 39.1    │
│ 37.8    │
│ 46.1    │
│ 50.0    │
│ 46.5    │
└─────────┘

In [42]:
df.get_column("bill_mm")

shape: (5,)
Series: 'bill_mm' [f64]
[
	39.1
	37.8
	46.1
	50.0
	46.5
]

In [20]:
df2 = pl.DataFrame(
    {
        "w": ["xx", "yy", "xx", "yy", "xx"],
        "x": [1, 2, 1, 4, -2],
        "y": [3.0, 4.5, 1.0, 2.5, -2.0],
        "z": ["a", "b", "a", "b", "b"],
    },
)
df2

shape: (5, 4)
┌─────┬─────┬──────┬─────┐
│ w   ┆ x   ┆ y    ┆ z   │
│ --- ┆ --- ┆ ---  ┆ --- │
│ str ┆ i64 ┆ f64  ┆ str │
╞═════╪═════╪══════╪═════╡
│ xx  ┆ 1   ┆ 3.0  ┆ a   │
│ yy  ┆ 2   ┆ 4.5  ┆ b   │
│ xx  ┆ 1   ┆ 1.0  ┆ a   │
│ yy  ┆ 4   ┆ 2.5  ┆ b   │
│ xx  ┆ -2  ┆ -2.0 ┆ b   │
└─────┴─────┴──────┴─────┘

In [21]:

df2.group_by(cs.string()).agg(cs.numeric().mean())

shape: (3, 4)
┌─────┬─────┬──────┬──────┐
│ w   ┆ z   ┆ x    ┆ y    │
│ --- ┆ --- ┆ ---  ┆ ---  │
│ str ┆ str ┆ f64  ┆ f64  │
╞═════╪═════╪══════╪══════╡
│ xx  ┆ b   ┆ -2.0 ┆ -2.0 │
│ yy  ┆ b   ┆ 3.0  ┆ 3.5  │
│ xx  ┆ a   ┆ 1.0  ┆ 2.0  │
└─────┴─────┴──────┴──────┘